name: CI

env:
  NODE_VERSION: "16.9.1"

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install deps
      run: npm ci
    - name: Build interfaces library
      run: |
        cd workspaces/mantella-interfaces
        npm run build
    - name: Test engine
      run: |
        cd workspaces/mantella-engine
        npm test
        npm run build
    - name: Test express wrapper
      run: |
        cd workspaces/mantella-express
        npm test
        npm run build

